name: app
description: A new Flutter project.
publish_to: 'none'
app_name: 'Universally'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  universally:
    path: ../
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  device_preview_minus: ^1.2.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/