name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  universally:
    path: ../
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  device_preview_minus: ^1.2.0
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/