name: universally
description: It depends on universally plug and can update the latest available version in time
version: 1.7.0
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^6.3.2
  carousel_slider: ^4.1.1
  connectivity_plus: ^3.0.2
  flutter_curiosity: ^4.1.0
  flutter_svg: ^1.1.6
  flutter_waya: ^3.5.1
  permission_handler: ^10.2.0
  provider: ^6.0.4
  url_launcher: ^6.1.7
  json_annotation: ^4.7.0
  keframe: ^3.0.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/res/svg/
