name: universally
description: A new Flutter universally package.
version: 0.0.2
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  connectivity: ^3.0.2
  dio: ^4.0.0-beta7
  flutter:
    sdk: flutter
  flutter_curiosity: ^2.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_waya: ^1.7.2
  json_annotation: ^4.0.0
  permission_handler: ^6.0.1
  provider: ^5.0.0
  pull_to_refresh: ^1.6.4
  shared_preferences: ^2.0.3
  url_launcher: ^6.0.2
  webview_flutter: ^2.0.2
