name: universally
description: It depends on universally plug and can update the latest available version in time
version: 1.0.0
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  dio: ^4.0.1
  cupertino_icons: ^1.0.4
  sqflite: ^2.0.0+4
  carousel_slider: ^4.0.0
  connectivity_plus: ^2.0.2
  path: ^1.8.0
  flutter:
    sdk: flutter
  flutter_easyrefresh: ^2.2.1
  flutter_curiosity: ^3.3.2
  flutter_svg: ^0.23.0+1
  flutter_waya: ^1.15.7
  fl_webview: ^0.2.5
  permission_handler: ^7.2.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  synchronized: ^3.0.0
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_lints: ^1.0.4
