name: universally
description: It depends on common plug and can update the latest available version in time
version: 0.2.3
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  connectivity: ^3.0.3
  flutter:
    sdk: flutter
  flutter_curiosity: ^2.0.0
  flutter_inappwebview: ^5.3.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_waya: ^1.8.7
  path_provider: ^2.0.1
  permission_handler: ^6.1.1
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  synchronized: ^3.0.0
  url_launcher: ^6.0.3