name: universally
description: It depends on universally plug and can update the latest available version in time
version: 1.1.0
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^6.2.1
  carousel_slider: ^4.1.1
  connectivity_plus: ^2.3.6+1
  flutter_curiosity: ^4.0.1+1
  flutter_svg: ^1.1.4
  flutter_waya: ^3.0.0
  permission_handler: ^10.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  synchronized: ^3.0.0+2
  url_launcher: ^6.1.5
  json_annotation: ^4.6.0
  keframe: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/res/svg/
