name: universally
description: It depends on common plug and can update the latest available version in time
version: 0.5.1
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  connectivity: ^3.0.6
  flutter:
    sdk: flutter
  flutter_curiosity: ^2.2.0
  flutter_easyrefresh: ^2.2.1
  flutter_inappwebview: ^5.3.2
  flutter_svg: ^0.22.0
  flutter_waya: ^1.10.1
  path_provider: ^2.0.2
  permission_handler: ^7.2.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  synchronized: ^3.0.0
  url_launcher: ^6.0.4