name: universally
description: It depends on universally plug and can update the latest available version in time
version: 0.9.1+3
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  dio: ^4.0.6
  extended_image: ^6.0.1
  carousel_slider: ^4.1.1
  connectivity_plus: ^2.3.5
  flutter:
    sdk: flutter
  flutter_easyrefresh: ^2.2.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_curiosity: ^3.5.1
  flutter_svg: ^1.0.3
  flutter_waya: ^1.21.3
  permission_handler: ^7.2.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  synchronized: ^3.0.0+2
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - lib/res/svg/
