name: universally
description: It depends on universally plug and can update the latest available version in time
version: 1.0.0+1
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  dio: ^4.0.6
  extended_image: ^6.2.1
  carousel_slider: ^4.1.1
  connectivity_plus: ^2.3.5
  flutter:
    sdk: flutter
  flutter_easyrefresh: ^2.2.2
  flutter_staggered_grid_view: ^0.6.2
  flutter_curiosity: ^4.0.1
  flutter_svg: ^1.1.1+1
  flutter_waya: ^2.2.0
  permission_handler: ^10.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  synchronized: ^3.0.0+2
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/res/svg/
