name: universally
description: It depends on universally plug and can update the latest available version in time
version: 6.4.3
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  carousel_slider: ^4.2.1
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  flutter_spinkit: ^5.2.0
  keframe: ^3.0.0
  extended_image: ^8.2.0
  flutter_curiosity: ^6.0.0
  flutter_waya: ^8.6.4
  fl_dio: ^0.2.0
  window_manager: ^0.3.7

  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  package_info_plus: ^5.0.1
  connectivity_plus: ^5.0.2
  android_intent_plus: ^4.0.3
  device_info_plus: ^9.1.1


  hive_flutter: ^1.1.0
  hive: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true