name: universally
description: It depends on universally plug and can update the latest available version in time
version: 0.6.3
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  dio: ^4.0.4
  extended_image: ^6.0.1
  cupertino_icons: ^1.0.4
  carousel_slider: ^4.0.0
  connectivity_plus: ^2.2.0
  path: ^1.8.0
  flutter:
    sdk: flutter
  flutter_easyrefresh: ^2.2.1
  flutter_curiosity: ^3.3.3
  flutter_svg: ^1.0.0
  flutter_waya:
    path: ../../github/flutter_waya
  permission_handler: ^7.2.0
  provider: ^6.0.1
  shared_preferences: ^2.0.10
  synchronized: ^3.0.0
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_lints: ^1.0.4
