name: universally
description: It depends on universally plug and can update the latest available version in time
version: 0.6.1
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  dio: ^4.0.4
  cupertino_icons: ^1.0.4
  sqflite: ^2.0.1
  carousel_slider: ^4.0.0
  connectivity_plus: ^2.1.0
  path: ^1.8.0
  flutter:
    sdk: flutter
  flutter_easyrefresh: ^2.2.1
  flutter_curiosity: ^3.3.3
  flutter_svg: ^1.0.0
  flutter_waya: ^1.16.0
  fl_webview: ^0.2.5
  permission_handler: ^7.2.0
  provider: ^6.0.1
  shared_preferences: ^2.0.10
  synchronized: ^3.0.0
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_lints: ^1.0.4
