name: universally
description: It depends on universally plug and can update the latest available version in time
version: 3.1.0
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  connectivity_plus: ^3.0.3
  flutter_curiosity: ^4.2.1
  flutter_svg: ^2.0.2
  flutter_waya: ^5.0.0+1
  permission_handler: ^10.2.0
  provider: ^6.0.5
  path_provider: ^2.0.12
  url_launcher: ^6.1.10
  json_annotation: ^4.8.0
  keframe: ^3.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  extended_image: ^7.0.2

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/res/svg/
