name: universally
description: It depends on universally plug and can update the latest available version in time
version: 10.0.0
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.9.0
  provider: ^6.1.5
  flutter_svg: ^2.1.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.4
  android_intent_plus: ^5.3.0
  device_info_plus: ^11.4.0

  flutter_spinkit: ^5.2.1
  keframe: ^3.0.0
  extended_image: ^10.0.1
  extended_image_library: ^5.0.0
  window_manager: ^0.4.3
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  flutter_curiosity: ^6.7.0
  flutter_waya: ^11.2.4
  fl_extended: ^1.8.0
  fl_list_wheel: ^0.0.3
  fl_scroll_view: ^1.0.1
  fl_dio: ^1.5.1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Universally
      fonts:
        - asset: assets/Universally.ttf