name: universally
description: It depends on universally plug and can update the latest available version in time
version: 5.0.0
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  carousel_slider: ^4.2.1
  connectivity_plus: ^4.0.1
  flutter_curiosity: ^4.3.1
  flutter_svg: ^2.0.7
  flutter_waya: ^8.0.1
  permission_handler: ^10.4.3
  provider: ^6.0.5
  path_provider: ^2.0.15
  url_launcher: ^6.1.12
  json_annotation: ^4.8.1
  keframe: ^3.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  extended_image: ^8.0.2

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true