name: universally
description: It depends on universally plug and can update the latest available version in time
version: 9.3.0
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  keframe: ^3.0.0
  extended_image: ^8.3.1
  extended_image_library: ^4.0.4
  window_manager: ^0.4.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  flutter_curiosity: ^6.3.1
  flutter_waya: ^9.9.0
  fl_extended: ^1.5.0
  fl_list_wheel: ^0.0.3
  fl_scroll_view: ^0.0.3
  fl_dio: ^1.2.2

  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.3
  connectivity_plus: ^6.0.5
  android_intent_plus: ^5.1.0
  device_info_plus: ^11.0.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Universally
      fonts:
        - asset: assets/Universally.ttf