name: universally
description: A new Flutter universally package.
version: 0.0.1
homepage: https://github.com/Wayaer/universally.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  permission_handler: ^5.0.1+2
  connectivity: ^2.0.2
  provider: ^4.3.3
  url_launcher: ^5.7.10
  webview_flutter: ^1.0.7
  path_provider: ^1.6.27
  dio: ^3.0.10
  flutter_curiosity: ^1.6.0
  flutter_waya: ^1.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
