name: universally
description: It depends on universally plug and can update the latest available version in time
version: 6.2.2
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: any
  json_annotation: any
  carousel_slider: any
  provider: any
  flutter_svg: any
  flutter_spinkit: any
  keframe: any
  extended_image: any
  flutter_curiosity: any
  flutter_waya: any
  fl_dio: any

  permission_handler: any
  path_provider: any
  url_launcher: any
  package_info_plus: any
  connectivity_plus: any
  android_intent_plus: any
  device_info_plus: any

  hive_flutter: ^1.1.0
  hive: ^2.2.3

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true