name: universally
description: It depends on universally plug and can update the latest available version in time
version: 7.1.3
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.0
  keframe: ^3.0.0
  extended_image: ^8.2.0
  extended_image_library: ^4.0.2
  flutter_curiosity: ^6.1.0
  flutter_waya: ^9.1.2
  fl_extended: ^0.2.0
  fl_dio: ^0.2.1
  window_manager: ^0.3.8

  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  package_info_plus: ^5.0.1
  connectivity_plus: ^5.0.2
  android_intent_plus: ^4.0.3
  device_info_plus: ^9.1.2

  hive_flutter: ^1.1.0
  hive: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Universally
      fonts:
        - asset: assets/Universally.ttf