name: universally
description: It depends on universally plug and can update the latest available version in time
version: 1.3.1
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^6.3.1
  carousel_slider: ^4.1.1
  connectivity_plus: ^2.3.7
  flutter_curiosity: ^4.0.1+1
  flutter_svg: ^1.1.5
  flutter_waya: ^3.2.0
  permission_handler: ^10.0.2
  provider: ^6.0.3
  url_launcher: ^6.1.6
  json_annotation: ^4.7.0
  keframe: ^3.0.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/res/svg/
