name: universally
description: It depends on universally plug and can update the latest available version in time
version: 6.0.6
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  carousel_slider: ^4.2.1
  provider: ^6.0.5
  flutter_svg: ^2.0.7

  keframe: ^3.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  extended_image: ^8.1.1
  flutter_curiosity: ^5.0.2
  flutter_waya: ^8.4.0
  fl_dio: ^0.1.0

  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  url_launcher: ^6.1.14
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.1
  android_intent_plus: ^4.0.3
  device_info_plus: ^9.1.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true