name: universally
description: It depends on universally plug and can update the latest available version in time
version: 9.4.1-oh
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_permission_handler
      path: permission_handler
      ref: br_permission_handler_v11.3.1_ohos
  path_provider:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages
      path: packages/path_provider/path_provider
      ref: br_path_provider-v2.1.4_ohos
  url_launcher:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages
      path: packages/url_launcher/url_launcher
      ref: br_url_launcher_v6.3.1_ohos
  shared_preferences:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages
      path: packages/shared_preferences/shared_preferences
      ref: br_shared_preferences-v2.5.3_ohos
  package_info_plus:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/package_info_plus/package_info_plus
      ref: br_package_info_plus-v8.1.0_ohos
  connectivity_plus:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/connectivity_plus/connectivity_plus
      ref: br_connectivity_plus-v6.1.0_ohos
  android_intent_plus: ^5.3.1
  device_info_plus:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/device_info_plus/device_info_plus
      ref: br_device_info_plus_v11.4.0_ohos

  extended_image: ^9.1.0
  extended_image_library: ^4.0.6
  window_manager: ^0.5.1
  flutter_curiosity: ^7.0.0

  path: ^1.9.0
  provider: ^6.1.5
  flutter_svg: ^2.2.0
  async: ^2.13.0
  decimal: ^3.2.4
  flutter_spinkit: ^5.2.2
  keframe: ^3.0.0

  flutter_waya: ^11.4.0
  fl_extended: ^1.9.3
  fl_list_wheel: ^0.0.3
  fl_scroll_view: ^1.0.1
  fl_dio: ^1.5.2

dependency_overrides:
  path_provider:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages
      path: packages/path_provider/path_provider
      ref: br_path_provider-v2.1.4_ohos

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Universally
      fonts:
        - asset: assets/Universally.ttf