name: universally
description: A new Flutter universally package.
version: 0.0.1
repository: https://github.com/Wayaer/universally.git
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  connectivity: ^2.0.2
  flutter:
    sdk: flutter
  flutter_curiosity:
    git:
      url: git://github.com/Wayaer/flutter_curiosity.git
      ref: master
  flutter_waya:
    git:
      url: git://github.com/Wayaer/flutter_waya.git
      ref: master
  flutter_svg: ^0.19.1
  json_annotation: ^3.1.0
  permission_handler: ^5.0.1+2
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
