name: universally
description: A new Flutter universally package.
version: 0.0.1
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  connectivity: ^2.0.2
  flutter:
    sdk: flutter
  flutter_curiosity:
    path: ../flutter_curiosity
  flutter_waya:
    path: ../flutter_waya
  shared_preferences: ^0.5.12+4
  permission_handler: ^5.0.1+2
  provider: ^4.3.3
  url_launcher: ^5.7.10
  webview_flutter: ^1.0.7
  path_provider: ^1.6.27
  dio: ^3.0.10
  flutter_svg: ^0.19.1
  json_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
