name: universally
description: It depends on universally plug and can update the latest available version in time
version: 11.1.2
repository: https://github.com/Wayaer/universally.git

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_intent_plus: ^6.0.0
  permission_handler: ^12.0.1
  permission_handler_harmonyos: ^0.0.1
  path_provider: ^2.1.5
  path_provider_harmonyos: ^0.0.1
  url_launcher: ^6.3.2
  url_launcher_harmonyos: ^0.0.1
  package_info_plus: ^9.0.0
  package_info_plus_harmonyos: ^0.0.1
  connectivity_plus: ^7.0.0
  connectivity_plus_harmonyos: ^0.0.1
  device_info_plus: ^12.1.0
  device_info_plus_harmonyos: ^0.0.3
  shared_preferences: ^2.5.3
  shared_preferences_harmonyos: ^0.0.1

  extended_image: ^10.0.1
  extended_image_library: ^5.0.1
  window_manager: ^0.5.1
  flutter_curiosity: ^7.0.0

  path: ^1.9.0
  provider: ^6.1.5+1
  flutter_svg: ^2.2.1
  async: ^2.13.0
  decimal: ^3.2.4
  flutter_spinkit: ^5.2.2
  keframe: ^3.0.0

  flutter_waya: ^11.4.0
  fl_extended: ^3.0.3
  fl_list_wheel: ^0.0.3
  fl_scroll_view: ^1.0.1
  fl_dio: ^1.5.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Universally
      fonts:
        - asset: assets/Universally.ttf